{"tag": "function", "depth": 1, "time": 1573565038.9927883, "data": {"name": "stop_app", "call_args": {"package": "com.mintegral.sdk.demo"}, "start_time": 1573565038.8627808, "ret": null, "end_time": 1573565038.9927883}}
{"tag": "function", "depth": 1, "time": 1573565039.5828218, "data": {"name": "start_app", "call_args": {"package": "com.mintegral.sdk.demo", "activity": null}, "start_time": 1573565038.9927883, "traceback": "Traceback (most recent call last):\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 368, in shell\n    out = self.raw_shell(cmd)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 326, in raw_shell\n    out = self.cmd(cmds, ensure_unicode=False)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 187, in cmd\n    raise AdbError(stdout, stderr)\nairtest.core.error.AdbError: stdout[b'  bash arg: -p\\r\\n  bash arg: com.mintegral.sdk.demo\\r\\n  bash arg: -c\\r\\n  bash arg: android.intent.category.LAUNCHER\\r\\n  bash arg: 1\\r\\n** No activities found to run, monkey aborted.\\r\\n'] stderr[b'args: [-p, com.mintegral.sdk.demo, -c, android.intent.category.LAUNCHER, 1]\\r\\n arg: \"-p\"\\r\\n arg: \"com.mintegral.sdk.demo\"\\r\\n arg: \"-c\"\\r\\n arg: \"android.intent.category.LAUNCHER\"\\r\\n arg: \"1\"\\r\\ndata=\"com.mintegral.sdk.demo\"\\r\\ndata=\"android.intent.category.LAUNCHER\"\\r\\n']\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 78, in wrapper\n    res = f(*args, **kwargs)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\api.py\", line 148, in start_app\n    G.DEVICE.start_app(package, activity)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\android.py\", line 120, in start_app\n    return self.adb.start_app(package, activity)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 1200, in start_app\n    self.shell(['monkey', '-p', package, '-c', 'android.intent.category.LAUNCHER', '1'])\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 370, in shell\n    raise AdbShellError(err.stdout, err.stderr)\nairtest.core.error.AdbShellError: stdout[b'  bash arg: -p\\r\\n  bash arg: com.mintegral.sdk.demo\\r\\n  bash arg: -c\\r\\n  bash arg: android.intent.category.LAUNCHER\\r\\n  bash arg: 1\\r\\n** No activities found to run, monkey aborted.\\r\\n'] stderr[b'args: [-p, com.mintegral.sdk.demo, -c, android.intent.category.LAUNCHER, 1]\\r\\n arg: \"-p\"\\r\\n arg: \"com.mintegral.sdk.demo\"\\r\\n arg: \"-c\"\\r\\n arg: \"android.intent.category.LAUNCHER\"\\r\\n arg: \"1\"\\r\\ndata=\"com.mintegral.sdk.demo\"\\r\\ndata=\"android.intent.category.LAUNCHER\"\\r\\n']\n", "end_time": 1573565039.5828218}}
{"tag": "info", "depth": 0, "time": 1573565039.5828218, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 368, in shell\n    out = self.raw_shell(cmd)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 326, in raw_shell\n    out = self.cmd(cmds, ensure_unicode=False)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 187, in cmd\n    raise AdbError(stdout, stderr)\nairtest.core.error.AdbError: stdout[b'  bash arg: -p\\r\\n  bash arg: com.mintegral.sdk.demo\\r\\n  bash arg: -c\\r\\n  bash arg: android.intent.category.LAUNCHER\\r\\n  bash arg: 1\\r\\n** No activities found to run, monkey aborted.\\r\\n'] stderr[b'args: [-p, com.mintegral.sdk.demo, -c, android.intent.category.LAUNCHER, 1]\\r\\n arg: \"-p\"\\r\\n arg: \"com.mintegral.sdk.demo\"\\r\\n arg: \"-c\"\\r\\n arg: \"android.intent.category.LAUNCHER\"\\r\\n arg: \"1\"\\r\\ndata=\"com.mintegral.sdk.demo\"\\r\\ndata=\"android.intent.category.LAUNCHER\"\\r\\n']\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\cli\\runner.py\", line 61, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"E:\\airtest_project-master\\air_case\\mintegral_demo.air\\mintegral_demo.py\", line 17, in <module>\n    start_app(\"com.mintegral.sdk.demo\")\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 78, in wrapper\n    res = f(*args, **kwargs)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\api.py\", line 148, in start_app\n    G.DEVICE.start_app(package, activity)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\android.py\", line 120, in start_app\n    return self.adb.start_app(package, activity)\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 1200, in start_app\n    self.shell(['monkey', '-p', package, '-c', 'android.intent.category.LAUNCHER', '1'])\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 370, in shell\n    raise AdbShellError(err.stdout, err.stderr)\nairtest.core.error.AdbShellError: stdout[b'  bash arg: -p\\r\\n  bash arg: com.mintegral.sdk.demo\\r\\n  bash arg: -c\\r\\n  bash arg: android.intent.category.LAUNCHER\\r\\n  bash arg: 1\\r\\n** No activities found to run, monkey aborted.\\r\\n'] stderr[b'args: [-p, com.mintegral.sdk.demo, -c, android.intent.category.LAUNCHER, 1]\\r\\n arg: \"-p\"\\r\\n arg: \"com.mintegral.sdk.demo\"\\r\\n arg: \"-c\"\\r\\n arg: \"android.intent.category.LAUNCHER\"\\r\\n arg: \"1\"\\r\\ndata=\"com.mintegral.sdk.demo\"\\r\\ndata=\"android.intent.category.LAUNCHER\"\\r\\n']\n"}}
